# --- Default ---

# Environment Options
num_process: 1

# Learning Options
learn_interval: 1
train_n: 1
max_epoch: 15000
batch_size: 2048

lr: 0.005
gamma: 0.95
tau: 0.001
target_update_interval: 1

memory: 'replay'
capacity: 10000000
test_interval: 25

q_nstep: 5
grad_norm_clip: 5
entropy_coef: 0.005